### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Sunyp-IM** [EricAlcaide/MiniFold#10]
Hello everyone,

I am trying to install minifold in my centos 7 system. when I run "pip install -r requirements.txt", I get the following error:

ERROR: No matching distribution found for tensorflow-gpu==1.12.0 (from -r requirements.txt (line 86))

After I remove the version number of  tensorflow-gpu in the requirements.txt file, tensorflow-gpu 2.0.0 is installed. However, I get the following errors:

Building wheel for pywinpty (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sunyp/software/build/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-22q2dxeq/pywinpty/setup.py'"'"'; __file__='"'"'/tmp/pip-install-22q2dxeq/pywinpty/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h5jnr0xb --python-tag cp37
       cwd: /tmp/pip-install-22q2dxeq/pywinpty/
  Complete output (27 lines):
  winpty/cywinpty.pyx: cannot find cimported module 'winpty._winpty'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/winpty
  copying winpty/ptyprocess.py -> build/lib.linux-x86_64-3.7/winpty
  copying winpty/winpty_wrapper.py -> build/lib.linux-x86_64-3.7/winpty
  copying winpty/__init__.py -> build/lib.linux-x86_64-3.7/winpty
  creating build/lib.linux-x86_64-3.7/winpty/tests
  copying winpty/tests/test_cywinpty.py -> build/lib.linux-x86_64-3.7/winpty/tests
  copying winpty/tests/test_ptyprocess.py -> build/lib.linux-x86_64-3.7/winpty/tests
  copying winpty/tests/test_winpty_wrapper.py -> build/lib.linux-x86_64-3.7/winpty/tests
  copying winpty/tests/__init__.py -> build/lib.linux-x86_64-3.7/winpty/tests
  creating build/lib.linux-x86_64-3.7/winpty/_winpty
  copying winpty/_winpty/__init__.py -> build/lib.linux-x86_64-3.7/winpty/_winpty
  running build_ext
  building 'winpty.cywinpty' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/winpty
  gcc -pthread -B /home/sunyp/software/build/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sunyp/software/build/anaconda3/include/python3.7m -c winpty/cywinpty.c -o build/temp.linux-x86_64-3.7/winpty/cywinpty.o
  winpty/cywinpty.c:597:21: fatal error: Windows.h: No such file or directory
   #include "Windows.h"
                       ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pywinpty

And: 

     ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Could you tell me how to solve the problem?

Thank you!

**Comment by EricAlcaide** [comment]
nobody has reported the same problem and it has been installed in all sort of systems. It seems a specific problem with your python environment. You could try using the conda-forge channel for anaconda and download tensorflow-gpu from there
