### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by PINGJINMING** [EricAlcaide/MiniFold#21]
When I running "predicting_angles.ipynb"
I got an error

`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-a97372b7e7cb> in <module>
      1 # Resnet (pre-act structure) with 34*42 columns as inputs - leaving a subset for validation
      2 his = model.fit(x_train, y_train, epochs=5, batch_size=16, verbose=1, shuffle=True,
----> 3                 validation_data=(x_test, y_test))

~/.local/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
   1211         else:
   1212             fit_inputs = x + y + sample_weights
-> 1213         self._make_train_function()
   1214         fit_function = self.train_function
   1215 

~/.local/lib/python3.6/site-packages/keras/engine/training.py in _make_train_function(self)
    314                     training_updates = self.optimizer.get_updates(
    315                         params=self._collected_trainable_weights,
--> 316                         loss=self.total_loss)
    317                 updates = self.updates + training_updates
    318 

~/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/.local/lib/python3.6/site-packages/keras/optimizers.py in get_updates(self, loss, params)
    538             if self.amsgrad:
    539                 vhat_t = K.maximum(vhat, v_t)
--> 540                 p_t = p - lr_t * m_t / (K.sqrt(vhat_t) + self.epsilon)
    541                 self.updates.append(K.update(vhat, vhat_t))
    542             else:

~/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py in binary_op_wrapper(x, y)
    886         try:
    887           y = ops.convert_to_tensor_v2(
--> 888               y, dtype_hint=x.dtype.base_dtype, name="y")
    889         except TypeError:
    890           # If the RHS is not a tensor, it might be a tensor aware object

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1143       name=name,
   1144       preferred_dtype=dtype_hint,
-> 1145       as_ref=False)
   1146 
   1147 

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accept_symbolic_tensors, accept_composite_tensors)
   1222 
   1223     if ret is None:
-> 1224       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1225 
   1226     if ret is NotImplemented:

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    303                                          as_ref=False):
    304   _ = as_ref
--> 305   return constant(v, dtype=dtype, name=name)
    306 
    307 

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name)
    244   """
    245   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 246                         allow_broadcast=True)
    247 
    248 

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    282       tensor_util.make_tensor_proto(
    283           value, dtype=dtype, shape=shape, verify_shape=verify_shape,
--> 284           allow_broadcast=allow_broadcast))
    285   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    286   const_tensor = g.create_op(

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    452   else:
    453     if values is None:
--> 454       raise ValueError("None values not supported.")
    455     # if dtype is provided, forces numpy array to be the type
    456     # provided if possible.

ValueError: None values not supported.
`
What should I do?

**Comment by EricAlcaide** [comment]
Hi there,
Haven't looked at the code in a while, so I would need to revisit the codebase.
Also, i don't think MiniFold is useful fr angle prediction. 
Just use it (or the idea behind it) for distance map prediction.

**Comment by PINGJINMING** [comment]
Thank you so muck,  I've solved it.
 There's something wrong with my computer environment.

**Comment by EricAlcaide** [comment]
angle prediction has been improved!
