### ISSUE TITLE
where is the file "90_full_under_200.txt"?

### ISSUE THREAD

**Issue by fakerXue** [EricAlcaide/MiniFold#28]
I can not find this file, please help me! thank you so much!

**Comment by EricAlcaide** [comment]
Yup, so you need to follow the instructions and create it by running the preprocessing julia script. 
I was too large to upload it to a github repo.

Hope this helps! If you can't run the script, leave me your email and I'll upload the file to a cloud provider and send you the link!

Good luck with your project!

**Comment by fakerXue** [comment]
> Yup, so you need to follow the instructions and create it by running the preprocessing julia script.
> I was too large to upload it to a github repo.
> 
> Hope this helps! If you can't run the script, leave me your email and I'll upload the file to a cloud provider and send you the link!
> 
> Good luck with your project!

Yes, thank you! I need that file, here is my Email 641018299@qq.com, or you can paste the file link at here, maybe somebody else need it also.

**Comment by EricAlcaide** [comment]
nice, uploading it in an hour or two

**Comment by EricAlcaide** [comment]
The file is very large (1.3 GB). I recommend you to generate them yourself via the Julia script provided in the "preprocessing" folder.
Here's the link: https://drive.google.com/file/d/13Ra4AizGIy_g38AuS1fwPgqVUtj51QDw/view?usp=sharing 
Let me know if you can't access the file and I'll share it with another platform via email.

**Comment by fakerXue** [comment]
the link is available!

**Comment by vinco0520** [comment]
> The file is very large (1.3 GB). I recommend you to generate them yourself via the Julia script provided in the "preprocessing" folder. Here's the link: https://drive.google.com/file/d/13Ra4AizGIy_g38AuS1fwPgqVUtj51QDw/view?usp=sharing Let me know if you can't access the file and I'll share it with another platform via email.

I didn't find the instructions to generating these files(70_full_under_200.txt, 90_full_under_200.txt) in the README, can you send me a copy as well?
