### ISSUE TITLE
what's the meaning of paramter "17"?

### ISSUE THREAD

**Issue by fakerXue** [EricAlcaide/MiniFold#29]
![微信图片_20200607162127](https://user-images.githubusercontent.com/6295482/83963790-08f80e80-a8db-11ea-84a0-af259b510283.png)

the picture from file "angle_data_preparation_py.ipynb"

**Comment by EricAlcaide** [comment]
so basically this 17 means that I'm taking the AAs from [-17, +17) wrt to the AA being predicted. That makes a 34AA-long sequence. The goal of the network is to predict the Angles of the AA based on its neighbouring AAs.

**Comment by fakerXue** [comment]
> so basically this 17 means that I'm taking the AAs from [-17, +17) wrt to the AA being predicted. That makes a 34AA-long sequence. The goal of the network is to predict the Angles of the AA based on its neighbouring AAs.

thank you! I got it
