### ISSUE TITLE
Julia preprocessing error

### ISSUE THREAD

**Issue by asawanggaa** [EricAlcaide/MiniFold#9]
when using Julia to preprocessing protein data, I get an error below:

ERROR: LoadError: syntax: line break in ":" expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1044
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] exec_options(::Base.JLOptions) at ./client.jl:266
 [5] _start() at ./client.jl:425
in expression starting at /disk2/minifold/MiniFold/preprocessing/get_proteins_under_200aa.jl:20

I'm a totally newbee in using Julia, can anyone help me about this

I use Julia version 1.0.4, and I make sure source_path and dst_path is right

**Comment by EricAlcaide** [comment]
Quick questions: 
1. Are you passing the raw_data_path and the destin_path via the console or via lines 15 and 16 of the script?
2. Are you using inverted slashes: "\"? If yes, consider switching to normal slashes: "/"

**Comment by asawanggaa** [comment]
I haven't passing the raw_data_path and Destin_path via the console because of the path in .jl file is the path where I store my data.
Also I solve this by using the julia_get_protein.ipynb file.I convert this file to a .jl first, and this file works well.
